before_script:
  - apt-get -q update
  - env DEBIAN_FRONTEND=noninteractive
    apt-get -q -y install --no-install-recommends
    aspcud apt-cudf
  - env DEBIAN_FRONTEND=noninteractive
    apt-get -q -y --solver aspcud
    -o Debug::pkgProblemResolver=yes
    install --no-install-recommends
    python3
    python3-setuptools
    python3-django
    python3-coverage
    python3-bcrypt
    python3-debian
    python3-celery
    python3-django-celery-beat
    python3-redis
    python3-fakeredis
    python3-lupa
    python3-debianbts
    python3-lxml
    ca-certificates
    libjs-jquery
    libjs-jquery-throttle-debounce
    libjs-jquery-isonscreen
    libjs-jquery-tablesorter
    git
    gnupg
    iso-codes
    dpkg-dev
    debhelper
    cdbs
    devscripts
    lintian
    $ADDITIONAL_PACKAGES

.test_template: &test
  variables:
    DJANGO_SETTINGS_MODULE: 'debexpo.settings.test'
  script:
    - python3 setup.py develop
    - python3 -m coverage run manage.py test -v 2 --exclude-tag nntp
    - python3 -m coverage report --include='debexpo*' --omit '*/nntp.py'
    - python3 -m coverage html --include='debexpo*' --omit '*/nntp.py'
  artifacts:
    paths:
      - htmlcov/

unstable:
  <<: *test
  image: debian:unstable

buster-bpo:
  <<: *test
  image: debian:buster-backports
  variables:
    ADDITIONAL_PACKAGES: python3-django/buster-backports
    DJANGO_SETTINGS_MODULE: 'debexpo.settings.test'

flake8:
  image: debian:unstable-slim
  before_script:
    - apt-get -q update
    - env DEBIAN_FRONTEND=noninteractive
      apt-get -q -y install --no-install-recommends
      python3-flake8
  script:
    - python3 -m flake8 debexpo/ tests/

trans:
  image: debian:unstable-slim
  allow_failure: true
  before_script:
    - apt-get -q update
    - env DEBIAN_FRONTEND=noninteractive
      apt-get -q -y install --no-install-recommends
      gettext
      python3
      python3-setuptools
      python3-django
      python3-debian
      python3-celery
      python3-django-celery-beat
      python3-redis
      python3-fakeredis
      python3-lupa
      python3-debianbts
      python3-lxml
  script:
    - (cd debexpo && python3 ../manage.py makemessages)
    - find debexpo -name '*.po' -exec
      msgfmt -c -v --statistics '{}' -o /dev/null ';' |& tee /tmp/trans
    - grep -zqv , /tmp/trans

migrations:
  image: debian:unstable-slim
  allow_failure: true
  before_script:
    - apt-get -q update
    - env DEBIAN_FRONTEND=noninteractive
      apt-get -q -y install --no-install-recommends
      gettext
      python3
      python3-setuptools
      python3-django
      python3-debian
      python3-celery
      python3-django-celery-beat
      python3-redis
      python3-fakeredis
      python3-lupa
      python3-debianbts
      python3-lxml
  script:
    - python3 manage.py makemigrations --check
