before_script:
  - apt-get -q update
  - env DEBIAN_FRONTEND=noninteractive
    apt-get -q -y install --no-install-recommends
    aspcud apt-cudf
  - env DEBIAN_FRONTEND=noninteractive
    apt-get -q -y --solver aspcud
    -o Debug::pkgProblemResolver=yes
    install --no-install-recommends
    python3
    python3-setuptools
    python3-django
    python3-coverage
    python3-bcrypt
    python3-debian
    python3-celery
    python3-django-celery-beat
    python3-redis
    python3-fakeredis
    python3-lupa
    python3-debianbts
    python3-lxml
    python3-distro-info
    python3-dulwich
    python3-djangorestframework
    python3-djangorestframework-extensions
    python3-django-filters
    python3-django-redis
    ca-certificates
    locales-all
    libjs-jquery
    libjs-jquery-throttle-debounce
    libjs-jquery-isonscreen
    libjs-jquery-tablesorter
    git
    gnupg
    iso-codes
    dpkg-dev
    debhelper
    cdbs
    devscripts
    lintian
    $ADDITIONAL_PACKAGES

.test_template: &test
  script:
    - python3 setup.py develop
    - python3 -m coverage run --branch manage.py test -v 2 --exclude-tag nntp
    - python3 -m coverage report --include='debexpo/*' --omit '*/nntp.py'
    - python3 -m coverage html --include='debexpo/*' --omit '*/nntp.py'
  artifacts:
    paths:
      - htmlcov/

unstable:
  <<: *test
  image: debian:unstable

trixie-bpo:
  <<: *test
  image: debian:trixie-backports

bookworm:
  <<: *test
  image: debian:bookworm-backports
  variables:
    ADDITIONAL_PACKAGES: lintian

# To re-enable when the first version of lintian land in bookworm-bpo
#bookworm-bpo:
#  <<: *test
#  image: debian:bookworm-backports
#  variables:
#    ADDITIONAL_PACKAGES: lintian/bookworm-backports

dependencies:
  image: debian:unstable
  script:
    - python3 setup.py develop | tee /tmp/deps.txt
    - (! grep Downloading /tmp/deps.txt)

flake8:
  image: debian:unstable-slim
  before_script:
    - apt-get -q update
    - env DEBIAN_FRONTEND=noninteractive
      apt-get -q -y install --no-install-recommends
      python3-flake8
  script:
    - python3 -m flake8 debexpo/ tests/

trans:
  image: debian:bookworm
  before_script:
    - apt-get -q update
    - env DEBIAN_FRONTEND=noninteractive
      apt-get -q -y install --no-install-recommends
      gettext
      git
      python3
      python3-setuptools
      python3-django
      python3-debian
      python3-celery
      python3-django-celery-beat
      python3-redis
      python3-fakeredis
      python3-lupa
      python3-debianbts
      python3-lxml
      python3-dulwich
      python3-djangorestframework
      python3-djangorestframework-extensions
      python3-django-filters
      python3-django-redis
  script:
    - (cd debexpo && python3 ../manage.py makemessages --all --keep-pot)
    - git checkout "*.po"
    - find debexpo -name '*.po' | while read po; do
        set -e;
        msgcmp --use-fuzzy --use-untranslated "${po}"
               "$(echo "${po}" | rev | cut -d / -f 4- | rev)/django.pot";
      done

migrations:
  image: debian:bookworm
  before_script:
    - apt-get -q update
    - env DEBIAN_FRONTEND=noninteractive
      apt-get -q -y install --no-install-recommends
      gettext
      python3
      python3-setuptools
      python3-django
      python3-debian
      python3-celery
      python3-django-celery-beat
      python3-redis
      python3-fakeredis
      python3-lupa
      python3-debianbts
      python3-lxml
      python3-dulwich
      python3-djangorestframework
      python3-djangorestframework-extensions
      python3-django-filters
      python3-django-redis
  script:
    - python3 manage.py makemigrations --check
