language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - sudo apt-get install python-lxml libapt-pkg-dev
  - pip install --editable .
# command to run tests
script: make test
