# Generated by Django 3.2.15 on 2022-09-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(blank=True, choices=[
                ('en', 'English'),
                ('fr', 'French')
            ], max_length=100, verbose_name='Language'),
        ),
    ]
