# Generated by Django 4.2.5 on 2023-10-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_locale_pt_br'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(blank=True, choices=[
                ('en', 'English'),
                ('de', 'German'),
                ('es', 'Spanish'),
                ('fa', 'Persian'),
                ('fr', 'French'),
                ('it', 'Italian'),
                ('ja', 'Japanese'),
                ('nl', 'Dutch'),
                ('pt', 'Portuguese'),
                ('pt-br', 'Portuguese (Brazil)'),
                ('ro', 'Romanian'),
                ('sv', 'Swedish'),
                ('zh-hans', 'Chinese (Simplified)')
            ], max_length=100, verbose_name='Language'),
        ),
    ]
