# Generated by Django 2.2.5 on 2020-01-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('package', models.CharField(max_length=100,
                                             verbose_name='Name')),
                ('version', models.CharField(max_length=100,
                                             verbose_name='Version')),
                ('component', models.CharField(max_length=32,
                                               verbose_name='Component')),
                ('distribution', models.CharField(max_length=32,
                                                  verbose_name='Distribution')),
                ('path', models.TextField(unique=True, verbose_name='Path')),
                ('size', models.IntegerField(verbose_name='Size')),
                ('sha256sum', models.CharField(max_length=64,
                                               verbose_name='SHA256')),
            ],
        ),
    ]
