# Generated by Django 2.2.17 on 2021-08-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryfile',
            name='path',
            field=models.TextField(verbose_name='Path'),
        ),
        migrations.AlterUniqueTogether(
            name='repositoryfile',
            unique_together={('package', 'version', 'path')},
        ),
    ]
