# Generated by Django 2.2.5 on 2019-12-29 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                 serialize=False, verbose_name='ID')),
                ('fingerprint', models.TextField(max_length=40,
                 verbose_name='Fingerprint')),
                ('key', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='keyring.Key'
                )),
            ],
        ),
    ]
